# Generated by Django 5.0.3 on 2024-03-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('maKhachHang', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('tenBanKe', models.CharField(max_length=250, null=True)),
                ('tenDoanhNghiep', models.CharField(max_length=250, null=True)),
                ('maNhomKH', models.CharField(max_length=50, null=True)),
                ('maNhanVienTT', models.CharField(max_length=250, null=True)),
                ('dienThoai', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('diaChi', models.CharField(max_length=350, null=True)),
                ('ngayLap', models.DateTimeField(null=True)),
                ('nguoiLap', models.CharField(max_length=50, null=True)),
                ('matKhau', models.CharField(max_length=250, null=True)),
                ('maKhachHangCap1', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_QLTT_KhachHang',
                'managed': False,
            },
        ),
    ]
