# Generated by Django 5.0.3 on 2024-08-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_statistic', '0002_salestatistic_last_month_turnover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaleStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('special_offer', 'mua ưu đãi'), ('reset_month', 'đặt lại hàng tháng'), ('reset_season', 'đặt lại the vụ'), ('admin_fix', 'admin tuỳ chỉnh')], max_length=128)),
                ('turnover', models.BigIntegerField(default=0)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_sale_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_statistic.usersalestatistic')),
            ],
        ),
    ]
