# Generated by Django 5.0.3 on 2024-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
