# Generated by Django 5.0.3 on 2024-05-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_remove_fileupload_order_productcatefile_productfile'),
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCertFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileupload')),
                ('register_cert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.registrationcert')),
            ],
        ),
    ]
