# Generated by Django 5.0.3 on 2024-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcertfile',
            name='docs_type',
            field=models.CharField(choices=[('gdk', 'GDK'), ('cbhq', 'CBHQ')], null=True),
        ),
    ]
