# Generated by Django 5.0.3 on 2024-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_productcatefile_docs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatefile',
            name='docs_type',
            field=models.CharField(choices=[('gdk', 'GDK'), ('cbhq', 'CBHQ'), ('image', 'Hình ảnh')], null=True),
        ),
    ]
