# Generated by Django 5.0.3 on 2024-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_alter_productcatefile_docs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='docs_type',
            field=models.CharField(choices=[('gdk', 'GDK'), ('cbhq', 'CBHQ'), ('image', 'Hình ảnh')], null=True),
        ),
    ]
