# Generated by Django 5.0.3 on 2024-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='alert_time',
            field=models.TimeField(),
        ),
    ]
