# Generated by Django 5.0.3 on 2024-06-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_banner_banneritem_banneritem_unique_banner_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banneritem',
            old_name='url',
            new_name='direct_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='display_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=24),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='banneritem',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
