# Generated by Django 5.0.3 on 2024-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneritem',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
    ]
