# Generated by Django 5.0.3 on 2024-10-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_banneritem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
    ]
