# Generated by Django 5.0.3 on 2024-06-03 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', 'migrate_susers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperm',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupperm',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.groupperm'),
        ),
    ]
