# Generated by Django 5.0.3 on 2024-03-22 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomUser',
            fields=[
                ('maNhom', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('tenNhom', models.CharField(max_length=255)),
                ('moTa', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_nhomuser',
            },
        ),
        migrations.CreateModel(
            name='QuyenHanUser',
            fields=[
                ('maQuyenHan', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('tenQuyen', models.CharField(max_length=255, unique=True)),
                ('moTa', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_quyenhan',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usercode', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('password', models.CharField(max_length=256)),
                ('khuVuc', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(default=None, max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('loaiUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_type.usertype', to_field='loaiUser')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('nhomUser', models.ManyToManyField(blank=True, related_name='users_rela', to='account.nhomuser')),
                ('quyenUser', models.ManyToManyField(blank=True, related_name='users_rela', to='account.quyenhanuser')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=255)),
                ('device', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('ip_address', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('status', models.CharField(default=None, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nhomuser',
            name='quyen',
            field=models.ManyToManyField(related_name='nhomUser_rela', to='account.quyenhanuser'),
        ),
        migrations.CreateModel(
            name='XacThuc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('xac_thuc', models.BooleanField(default=False)),
                ('ma_xac_thuc', models.CharField(max_length=64)),
                ('loai_xac_thuc', models.CharField(default=None, max_length=128)),
                ('moTa', models.TextField(default=None, null=True)),
                ('time_xac_thuc', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
