# Generated by Django 5.0.3 on 2024-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperm',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
