# Generated by Django 5.0.3 on 2024-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', 'migrate_susers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'employee'), ('client', 'client'), ('farmer', 'farmer')], default='client', max_length=24),
        ),
    ]
