# Generated by Django 5.0.3 on 2024-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
