# Generated by Django 5.0.3 on 2024-03-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loaiUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_type.usertype', to_field='loaiUser'),
        ),
    ]
