# Generated by Django 5.0.3 on 2024-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomUser',
            fields=[
                ('maNhom', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('tenNhom', models.CharField(max_length=255)),
                ('moTa', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuyenHanUser',
            fields=[
                ('maQuyenHan', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('tenQuyen', models.CharField(max_length=255, unique=True)),
                ('moTa', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='khuVuc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usercode',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nhomUser',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.nhomuser'),
        ),
        migrations.AddField(
            model_name='nhomuser',
            name='permissions',
            field=models.ManyToManyField(related_name='nhomUser', to='account.quyenhanuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='quyenUser',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.quyenhanuser'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
