# Generated by Django 5.0.3 on 2024-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tokenmapping_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_token',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='device_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('sub', 'sub')], default='sub', max_length=64),
        ),
    ]
