# Generated by Django 5.0.3 on 2024-06-20 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_group', to='account.groupperm')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_group', to='account.perm')),
            ],
            options={
                'db_table': 'users_groupperm_perm',
            },
        ),
    ]
