# Generated by Django 5.0.3 on 2024-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_device_token_phonenumber_device_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
