# Generated by Django 5.0.3 on 2024-06-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_groupperm_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperm',
            name='perm',
            field=models.ManyToManyField(blank=True, through='account.GroupPermPerms', to='account.perm'),
        ),
    ]
