# Generated by Django 5.0.3 on 2024-06-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_groupperm_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperm',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perm',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
