# Generated by Django 5.0.3 on 2024-06-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='product.product'),
        ),
    ]
