# Generated by Django 5.0.3 on 2024-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('annual', 'annual'), ('infrequent', 'infrequent')], default='infrequent', max_length=64),
        ),
    ]
