# Generated by Django 5.0.3 on 2024-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_pricelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('sub', 'sub')], default='sub', max_length=64),
        ),
    ]
