# Generated by Django 5.0.3 on 2024-07-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_alter_specialoffer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='box_can_use',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='quantity_can_use',
            field=models.IntegerField(null=True),
        ),
    ]
