# Generated by Django 5.0.3 on 2024-08-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0003_specialoffer_priority_alter_specialoffer_box_can_use_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfSeason',
        ),
    ]
