# Generated by Django 5.0.3 on 2024-05-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0003_pointofseason'),
        ('product', 'migrate_old_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('target', models.BigIntegerField(default=0)),
                ('quantity_can_use', models.FloatField(null=True)),
                ('box_can_use', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=24, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_list.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOfferProduct',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('special_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.specialoffer')),
            ],
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='product',
            field=models.ManyToManyField(through='price_list.SpecialOfferProduct', to='product.product'),
        ),
    ]
