# Generated by Django 5.0.3 on 2024-05-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0004_specialoffer_specialofferproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='client_id',
        ),
    ]
