# Generated by Django 5.0.3 on 2024-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0005_specialoffer_for_nvtt_specialoffer_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='type',
        ),
    ]
