# Generated by Django 5.0.3 on 2024-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0005_remove_specialoffer_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialofferproduct',
            old_name='quantity',
            new_name='quantity_in_box',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='type_list',
            field=models.CharField(default='percent', max_length=24),
        ),
        migrations.AddField(
            model_name='specialofferproduct',
            name='point',
            field=models.FloatField(null=True),
        ),
    ]
