# Generated by Django 5.0.3 on 2024-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0005_remove_livestreamproductlist_live_stream_and_more'),
        ('price_list', '0007_alter_specialoffer_type_list'),
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='date_start',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='live_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='livestream.livestream'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='price_list.pricelist'),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='product.product'),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='special_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='price_list.specialoffer'),
        ),
    ]
