# Generated by Django 5.0.3 on 2024-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0008_remove_specialoffer_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='count_turnover',
            field=models.BooleanField(default=False),
        ),
    ]
