# Generated by Django 5.0.3 on 2024-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0009_specialoffer_count_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialofferproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='quantity_in_box',
            field=models.FloatField(default=0),
        ),
    ]
