# Generated by Django 5.0.3 on 2024-05-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0010_specialofferproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialofferproduct',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='quantity_in_box',
            field=models.IntegerField(default=0),
        ),
    ]
