# Generated by Django 5.0.3 on 2024-05-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0012_alter_specialofferproduct_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialofferproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
