# Generated by Django 5.0.3 on 2024-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0013_alter_specialofferproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialofferproduct',
            name='cashback',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specialofferproduct',
            name='max_order_box',
            field=models.IntegerField(null=True),
        ),
    ]
