# Generated by Django 5.0.3 on 2024-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='created_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
