# Generated by Django 5.0.3 on 2024-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position_id',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ManyToManyField(to='employee_profile.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.ManyToManyField(to='employee_profile.position'),
        ),
    ]
