# Generated by Django 5.0.3 on 2024-05-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_employeeprofile_address_employeeprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
