# Generated by Django 5.0.3 on 2024-06-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_remove_employeeprofile_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='fullname',
            new_name='register_name',
        ),
    ]
