# Generated by Django 5.0.3 on 2024-03-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhomKH',
            fields=[
                ('maNhom', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tenNhom', models.CharField(max_length=255)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('nguoiLap', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maNhomCha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kh_nhomkh.nhomkh')),
            ],
            options={
                'db_table': 'kh_nhomkh',
            },
        ),
    ]
