# Generated by Django 5.0.3 on 2024-03-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh_nhomkh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhomkh',
            name='moTa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
