# Generated by Django 5.0.3 on 2024-05-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_offer_consider',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_so',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
