# Generated by Django 5.0.3 on 2024-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product'),
        ),
    ]
