# Generated by Django 5.0.3 on 2024-05-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetail_note_alter_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='point_per_box',
        ),
        migrations.AddField(
            model_name='order',
            name='order_point',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='point_get',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_box',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price_list_so',
            field=models.FloatField(null=True),
        ),
    ]
