# Generated by Django 5.0.3 on 2024-06-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nvtt_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
