# Generated by Django 5.0.3 on 2024-08-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_seasonalstatistic_seasonalstatisticuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalstatistic',
            name='type',
            field=models.CharField(choices=[('point', 'điểm'), ('turnover', 'doanh số')]),
        ),
    ]
