# Generated by Django 5.0.3 on 2024-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_seasonalstatistic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
