# Generated by Django 5.0.3 on 2024-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderdetail_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='price_list_so',
            new_name='price_so',
        ),
    ]
