# Generated by Django 5.0.3 on 2024-10-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_npp_id'),
        ('price_list', '0006_remove_pricelist_type'),
        ('product', '0001_registrationcert_name_alter_registrationcert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_special_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='price_list.specialoffer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_price_list', to='price_list.pricelist'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='product.product'),
        ),
    ]
