# Generated by Django 5.0.3 on 2024-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_id_offer_consider_remove_order_id_so_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('date_get', models.DateField(null=True)),
                ('date_company_get', models.DateTimeField(null=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('date_delay', models.IntegerField(default=0)),
                ('list_type', models.CharField(max_length=24, null=True)),
                ('price_list_id', models.CharField(max_length=255, null=True)),
                ('is_so', models.BooleanField(default=False, null=True)),
                ('count_turnover', models.BooleanField(default=True)),
                ('minus_so_box', models.BigIntegerField(default=None, null=True)),
                ('new_special_offer', models.CharField(max_length=255, null=True)),
                ('order_point', models.FloatField(null=True)),
                ('order_price', models.FloatField(default=0, null=True)),
                ('nvtt_id', models.CharField(max_length=64, null=True)),
                ('npp_id', models.CharField(max_length=64, null=True)),
                ('created_by', models.CharField(max_length=64, null=True)),
                ('note', models.TextField(null=True)),
                ('status', models.CharField(max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255, null=True)),
                ('order_quantity', models.IntegerField(default=1, null=True)),
                ('order_box', models.FloatField(default=0, null=True)),
                ('price_so', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
                ('product_price', models.BigIntegerField(null=True)),
                ('point_get', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderBackup',
        ),
        migrations.DeleteModel(
            name='OrderBackupDetail',
        ),
    ]
