# Generated by Django 5.0.3 on 2024-05-29 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNumber',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_close', models.DateField()),
                ('range_number', models.IntegerField()),
                ('limit_repeat', models.IntegerField(default=1)),
                ('point_exchange', models.FloatField(default=1)),
                ('status', models.CharField(default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberList',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('repeat_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_list', to='pick_number.eventnumber')),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_pick', models.IntegerField(default=0)),
                ('turn_selected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to='pick_number.eventnumber')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to='pick_number.numberlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
