# Generated by Django 5.0.3 on 2024-06-23 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pick_number', '0001_initial'),
        ('price_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnumber',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_number', to='price_list.pricelist'),
        ),
        migrations.AddField(
            model_name='numberlist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_list', to='pick_number.eventnumber'),
        ),
        migrations.AddField(
            model_name='numberselected',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_selected', to='pick_number.numberlist'),
        ),
        migrations.AddField(
            model_name='userjoinevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to='pick_number.eventnumber'),
        ),
        migrations.AddField(
            model_name='userjoinevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numberselected',
            name='user_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_selected', to='pick_number.userjoinevent'),
        ),
        migrations.AlterUniqueTogether(
            name='numberselected',
            unique_together={('user_event', 'number')},
        ),
    ]
