# Generated by Django 5.0.3 on 2024-05-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pick_number', '0002_remove_userjoinevent_number_alter_userjoinevent_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numberselected',
            unique_together={('user_event', 'number')},
        ),
    ]
