# Generated by Django 5.0.3 on 2024-08-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tokenmapping_phone_number'),
        ('pick_number', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinevent',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_join_event', to='account.phonenumber'),
        ),
        migrations.CreateModel(
            name='PrizeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=128)),
                ('reward_value', models.CharField(max_length=256, null=True)),
                ('reward_number', models.IntegerField(default=0)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_event', to='pick_number.eventnumber')),
            ],
        ),
        migrations.CreateModel(
            name='AwardNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_number', to='pick_number.prizeevent')),
            ],
        ),
    ]
