# Generated by Django 5.0.3 on 2024-05-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_number', '0003_alter_numberselected_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinevent',
            name='bonus_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userjoinevent',
            name='total_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userjoinevent',
            name='used_point',
            field=models.FloatField(default=0),
        ),
    ]
