# Generated by Django 5.0.3 on 2024-05-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_number', '0004_userjoinevent_bonus_point_userjoinevent_total_point_and_more'),
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnumber',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_number', to='price_list.pricelist'),
        ),
    ]
