# Generated by Django 5.0.3 on 2024-04-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('nvtt_id', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('client_lv1_id', models.CharField(max_length=255, null=True)),
                ('created_by', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_group.clientgroup')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients_profile',
            },
        ),
    ]
