# Generated by Django 5.0.3 on 2024-06-23 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_profile.clientgroup')),
            ],
            options={
                'db_table': 'client_group',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('nvtt_id', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('client_lv1_id', models.CharField(max_length=255, null=True)),
                ('is_npp', models.BooleanField(default=False)),
                ('created_by', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.clientgroup')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients_profile',
            },
        ),
    ]
