# Generated by Django 5.0.3 on 2024-08-30 02:42

from django.db import migrations, models

from utils.helpers import self_id


def move_id_to_name(apps, schema_editor):
    RegistrationCert = apps.get_model('product', 'RegistrationCert')
    for cert in RegistrationCert.objects.all():
        cert.name = cert.id  # Di chuyển giá trị từ id cũ sang name
        cert.save()


class Migration(migrations.Migration):
    dependencies = [
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcert',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(move_id_to_name),
        migrations.AlterField(
            model_name='registrationcert',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
