# Generated by Django 5.0.3 on 2024-03-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NVChucDanh',
            fields=[
                ('maChucDanh', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tenChucDanh', models.CharField(max_length=255)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nv_chucdanh',
            },
        ),
        migrations.CreateModel(
            name='NVPhongBan',
            fields=[
                ('maPhongBan', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tenPhongBan', models.CharField(max_length=255)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nv_phongban',
            },
        ),
        migrations.CreateModel(
            name='NVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gioiTinh', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maChucDanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nv_profile.nvchucdanh')),
                ('maNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maPhongBan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nv_profile.nvphongban')),
            ],
            options={
                'db_table': 'nv_profile',
            },
        ),
    ]
