# Generated by Django 5.0.3 on 2024-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='allow_order',
            field=models.BooleanField(default=True),
        ),
    ]
