# Generated by Django 5.0.3 on 2024-05-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_tokenmapping'),
        ('livestream', '0001_initial'),
        ('product', 'migrate_old_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamcomment',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber'),
        ),
        migrations.AlterField(
            model_name='livestreamcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LiveStreamProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allow_order', models.FloatField(default=1)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreamProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('point', models.FloatField(default=0, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('livestream_product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestreamproductlist')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreamTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_join', models.TimeField(null=True)),
                ('time_leave', models.TimeField(null=True)),
                ('time_watch', models.TimeField(null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber')),
            ],
        ),
    ]
