# Generated by Django 5.0.3 on 2024-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_livestreamcomment_phone_alter_livestreamcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamproduct',
            name='max_purchase',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livestreamproduct',
            name='total_item',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livestreamproductlist',
            name='turn_order',
            field=models.IntegerField(default=1),
        ),
    ]
