# Generated by Django 5.0.3 on 2024-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_livestream_allow_comment_livestream_allow_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamstatistic',
            name='fake_order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestreamstatistic',
            name='fake_viewer_number',
            field=models.IntegerField(default=0),
        ),
    ]
