# Generated by Django 5.0.3 on 2024-05-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_tokenmapping'),
        ('livestream', '0003_livestreamproduct_max_purchase_and_more'),
        ('product', 'migrate_old_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestream_product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestreamproductlist')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLiveProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_price', models.BigIntegerField(default=0)),
                ('point_get', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.orderliveproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
