# Generated by Django 5.0.3 on 2024-05-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_orderliveproduct_orderliveproductdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreamproductlist',
            name='live_stream',
        ),
        migrations.RemoveField(
            model_name='orderliveproduct',
            name='livestream_product_list',
        ),
        migrations.RemoveField(
            model_name='orderliveproduct',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderliveproductdetails',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderliveproductdetails',
            name='product',
        ),
        migrations.CreateModel(
            name='LiveStreamPeekView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_livestream', models.IntegerField(default=0)),
                ('out_livestream', models.IntegerField(default=0)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
            ],
        ),
        migrations.DeleteModel(
            name='LiveStreamProduct',
        ),
        migrations.DeleteModel(
            name='LiveStreamProductList',
        ),
        migrations.DeleteModel(
            name='OrderLiveProduct',
        ),
        migrations.DeleteModel(
            name='OrderLiveProductDetails',
        ),
    ]
