# Generated by Django 5.0.3 on 2024-05-20 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_tokenmapping'),
        ('livestream', '0005_remove_livestreamproductlist_live_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamOfferRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber')),
            ],
        ),
    ]
