# Generated by Django 5.0.3 on 2024-05-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_livestreamofferregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestreampeekview',
            name='live_stream',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream'),
        ),
    ]
